// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sysbimbo.Api.Data;

#nullable disable

namespace Sysbimbo.Api.Data.Migrations.FormularioPostgres
{
    [DbContext(typeof(FormularioDbContext))]
    [Migration("20260812215904_AddConfigurableUsersAndForms")]
    partial class AddConfigurableUsersAndForms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_claim_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("roles_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_claim_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("proveedor");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("clave_proveedor");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("nombre_proveedor");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("proveedor");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("usuarios_tokens", (string)null);
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.ArchivoFormulario", b =>
                {
                    b.Property<long>("ArchivoFormularioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("archivo_formulario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ArchivoFormularioId"));

                    b.Property<string>("ClaveObjeto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("clave_objeto");

                    b.Property<Guid?>("CreadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_sha256");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("proveedor");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_contenido");

                    b.HasKey("ArchivoFormularioId")
                        .HasName("pk_archivos_formulario");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("Proveedor", "ClaveObjeto")
                        .IsUnique()
                        .HasDatabaseName("ux_archivos_formulario_objeto");

                    b.ToTable("archivos_formulario", null, t =>
                        {
                            t.HasCheckConstraint("ck_archivos_formulario_tamano", "tamano_bytes >= 0");
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.Cliente", b =>
                {
                    b.Property<long>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClienteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("ClienteId")
                        .HasName("pk_clientes");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_clientes_codigo");

                    b.ToTable("clientes", (string)null);

                    b.HasData(
                        new
                        {
                            ClienteId = 1L,
                            Activo = true,
                            Codigo = "BIMBO",
                            FechaCreacion = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Bimbo"
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.ClienteTienda", b =>
                {
                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("TiendaCadenaKey")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("tienda_cadena_key");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ClienteId", "TiendaCadenaKey")
                        .HasName("pk_clientes_tiendas");

                    b.HasIndex("TiendaCadenaKey");

                    b.ToTable("clientes_tiendas", (string)null);
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.DimTiendaMaestraExport", b =>
                {
                    b.Property<string>("TiendaCadenaKey")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("tienda_cadena_key");

                    b.Property<string>("Cadena")
                        .HasColumnType("text")
                        .HasColumnName("cadena");

                    b.Property<string>("Canal")
                        .HasColumnType("text")
                        .HasColumnName("canal");

                    b.Property<long?>("CantidadRegistros")
                        .HasColumnType("bigint")
                        .HasColumnName("cantidad_registros");

                    b.Property<string>("CodigoTiendaB2B")
                        .HasColumnType("text")
                        .HasColumnName("codigo_tienda_b2b");

                    b.Property<string>("CodigoTiendaB2BPrefijo")
                        .HasColumnType("text")
                        .HasColumnName("codigo_tienda_b2b_prefijo");

                    b.Property<string>("Formato")
                        .HasColumnType("text")
                        .HasColumnName("formato");

                    b.Property<string>("FuenteTienda")
                        .HasColumnType("text")
                        .HasColumnName("fuente_tienda");

                    b.Property<string>("Gestor")
                        .HasColumnType("text")
                        .HasColumnName("gestor");

                    b.Property<string>("LimaProvincias")
                        .HasColumnType("text")
                        .HasColumnName("lima_provincias");

                    b.Property<string>("NombreTienda")
                        .HasColumnType("text")
                        .HasColumnName("nombre_tienda");

                    b.Property<string>("NombreTiendaBimbo")
                        .HasColumnType("text")
                        .HasColumnName("nombre_tienda_bimbo");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("provincia");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("Ruta")
                        .HasColumnType("text")
                        .HasColumnName("ruta");

                    b.Property<string>("Supervisor")
                        .HasColumnType("text")
                        .HasColumnName("supervisor");

                    b.Property<string>("TipoLocal")
                        .HasColumnType("text")
                        .HasColumnName("tipo_local");

                    b.Property<DateTime?>("UltimaFecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultima_fecha");

                    b.Property<string>("Vendedor")
                        .HasColumnType("text")
                        .HasColumnName("vendedor");

                    b.HasKey("TiendaCadenaKey")
                        .HasName("pk_tiendas");

                    b.HasIndex("Formato")
                        .HasDatabaseName("ix_tiendas_formato");

                    b.HasIndex("NombreTiendaBimbo")
                        .HasDatabaseName("ix_tiendas_nombre_bimbo");

                    b.ToTable("tiendas", (string)null);
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.Formulario", b =>
                {
                    b.Property<long>("FormularioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("formulario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FormularioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ruta");

                    b.HasKey("FormularioId")
                        .HasName("pk_formularios");

                    b.HasAlternateKey("FormularioId", "ClienteId")
                        .HasName("ak_formularios_cliente");

                    b.HasIndex("ClienteId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_formularios_cliente_codigo");

                    b.ToTable("formularios", (string)null);

                    b.HasData(
                        new
                        {
                            FormularioId = 1L,
                            Activo = true,
                            ClienteId = 1L,
                            Codigo = "CONTROL_MATERIAL_IMPULSO",
                            Descripcion = "Registro de evidencias y cumplimiento diario por material de impulso.",
                            FechaCreacion = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Control de material",
                            Orden = 1,
                            Ruta = "/habilitar-tienda"
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.FormularioOpcion", b =>
                {
                    b.Property<long>("FormularioOpcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("formulario_opcion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FormularioOpcionId"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Configuracion")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuracion");

                    b.Property<long>("FormularioId")
                        .HasColumnType("bigint")
                        .HasColumnName("formulario_id");

                    b.Property<bool>("Habilitada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("habilitada");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("FormularioOpcionId")
                        .HasName("pk_formularios_opciones");

                    b.HasIndex("FormularioId", "Clave")
                        .IsUnique()
                        .HasDatabaseName("ux_formularios_opciones_clave");

                    b.ToTable("formularios_opciones", (string)null);

                    b.HasData(
                        new
                        {
                            FormularioOpcionId = 1L,
                            Clave = "LOGIN_REQUERIDO",
                            FormularioId = 1L,
                            Habilitada = false,
                            Nombre = "Inicio de sesion"
                        },
                        new
                        {
                            FormularioOpcionId = 2L,
                            Clave = "ROLES_HABILITADOS",
                            FormularioId = 1L,
                            Habilitada = false,
                            Nombre = "Control por roles"
                        },
                        new
                        {
                            FormularioOpcionId = 3L,
                            Clave = "FOTO_INICIO_OBLIGATORIA",
                            FormularioId = 1L,
                            Habilitada = false,
                            Nombre = "Foto de inicio obligatoria"
                        },
                        new
                        {
                            FormularioOpcionId = 4L,
                            Clave = "CONTROL_TIENDA",
                            FormularioId = 1L,
                            Habilitada = true,
                            Nombre = "Control por tienda"
                        },
                        new
                        {
                            FormularioOpcionId = 5L,
                            Clave = "CONTROL_SUPERVISOR",
                            FormularioId = 1L,
                            Habilitada = false,
                            Nombre = "Control por supervisor"
                        },
                        new
                        {
                            FormularioOpcionId = 6L,
                            Clave = "CIERRE_JORNADA_AUTOMATICO",
                            Configuracion = "{\"hora\":\"23:59:59\",\"zonaHoraria\":\"America/Lima\"}",
                            FormularioId = 1L,
                            Habilitada = true,
                            Nombre = "Cierre automatico de jornada"
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.FormularioRegistro", b =>
                {
                    b.Property<long>("FormularioRegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("formulario_registro_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FormularioRegistroId"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Datos")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_finalizacion");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("FormularioId")
                        .HasColumnType("bigint")
                        .HasColumnName("formulario_id");

                    b.Property<long?>("JornadaUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("jornada_usuario_id");

                    b.Property<Guid?>("SupervisorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("supervisor_usuario_id");

                    b.Property<string>("TiendaCadenaKey")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("tienda_cadena_key");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("FormularioRegistroId")
                        .HasName("pk_formularios_registros");

                    b.HasIndex("JornadaUsuarioId");

                    b.HasIndex("SupervisorUsuarioId");

                    b.HasIndex("ClienteId", "TiendaCadenaKey");

                    b.HasIndex("FormularioId", "ClienteId");

                    b.HasIndex("FormularioId", "FechaInicio")
                        .HasDatabaseName("ix_formularios_registros_fecha");

                    b.HasIndex("UsuarioId", "FechaInicio")
                        .HasDatabaseName("ix_formularios_registros_usuario_fecha");

                    b.ToTable("formularios_registros", null, t =>
                        {
                            t.HasCheckConstraint("ck_formularios_registros_fechas", "fecha_finalizacion IS NULL OR fecha_finalizacion >= fecha_inicio");
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.FormularioRegistroArchivo", b =>
                {
                    b.Property<long>("FormularioRegistroId")
                        .HasColumnType("bigint")
                        .HasColumnName("formulario_registro_id");

                    b.Property<long>("ArchivoFormularioId")
                        .HasColumnType("bigint")
                        .HasColumnName("archivo_formulario_id");

                    b.Property<string>("Tipo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.HasKey("FormularioRegistroId", "ArchivoFormularioId", "Tipo")
                        .HasName("pk_formularios_registros_archivos");

                    b.HasIndex("ArchivoFormularioId");

                    b.ToTable("formularios_registros_archivos", (string)null);
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.FotoMaterialImpulso", b =>
                {
                    b.Property<long>("FotoMaterialImpulsoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("foto_material_impulso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FotoMaterialImpulsoId"));

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaCaptura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_captura")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("MaterialImpulsoTiendaId")
                        .HasColumnType("bigint")
                        .HasColumnName("material_impulso_tienda_id");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nombre_archivo");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TiendaCadenaKey")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("tienda_cadena_key");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_contenido");

                    b.HasKey("FotoMaterialImpulsoId")
                        .HasName("pk_fotos_material_impulso");

                    b.HasIndex("MaterialImpulsoTiendaId", "FechaCaptura")
                        .HasDatabaseName("ix_fotos_material_fecha");

                    b.ToTable("fotos_material_impulso", null, t =>
                        {
                            t.HasCheckConstraint("ck_fotos_material_impulso_tamano", "tamano_bytes > 0");
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.JornadaUsuario", b =>
                {
                    b.Property<long>("JornadaUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("jornada_usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JornadaUsuarioId"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("direccion_ip");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dispositivo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaJornada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_jornada");

                    b.Property<long>("FormularioId")
                        .HasColumnType("bigint")
                        .HasColumnName("formulario_id");

                    b.Property<long?>("FotoInicioArchivoId")
                        .HasColumnType("bigint")
                        .HasColumnName("foto_inicio_archivo_id");

                    b.Property<DateTime>("HoraIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_ingreso");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_salida");

                    b.Property<Guid?>("SupervisorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("supervisor_usuario_id");

                    b.Property<string>("TiendaCadenaKey")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("tienda_cadena_key");

                    b.Property<string>("TipoCierre")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_cierre");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("JornadaUsuarioId")
                        .HasName("pk_jornadas_usuarios");

                    b.HasIndex("FotoInicioArchivoId");

                    b.HasIndex("SupervisorUsuarioId");

                    b.HasIndex("ClienteId", "TiendaCadenaKey");

                    b.HasIndex("FechaJornada", "Estado")
                        .HasDatabaseName("ix_jornadas_fecha_estado");

                    b.HasIndex("FormularioId", "ClienteId");

                    b.HasIndex("UsuarioId", "FormularioId", "FechaJornada")
                        .IsUnique()
                        .HasDatabaseName("ux_jornadas_usuario_formulario_fecha");

                    b.ToTable("jornadas_usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_jornadas_usuarios_horas", "hora_salida IS NULL OR hora_salida >= hora_ingreso");
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.MaterialImpulsoTienda", b =>
                {
                    b.Property<long>("MaterialImpulsoTiendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("material_impulso_tienda_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MaterialImpulsoTiendaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CuotaDiaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cuota_diaria");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreMaterial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_material");

                    b.Property<string>("TiendaCadenaKey")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("tienda_cadena_key");

                    b.HasKey("MaterialImpulsoTiendaId")
                        .HasName("pk_materiales_impulso_tienda");

                    b.HasIndex("TiendaCadenaKey", "Activo")
                        .HasDatabaseName("ix_materiales_tienda_activo");

                    b.HasIndex("TiendaCadenaKey", "NombreMaterial")
                        .IsUnique()
                        .HasDatabaseName("ux_materiales_tienda_nombre_activo")
                        .HasFilter("activo = TRUE");

                    b.ToTable("materiales_impulso_tienda", null, t =>
                        {
                            t.HasCheckConstraint("ck_materiales_impulso_tienda_cuota_diaria", "cuota_diaria >= 0");
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.SupervisorPersonal", b =>
                {
                    b.Property<long>("SupervisorPersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("supervisor_personal_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SupervisorPersonalId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<Guid>("PersonalUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_usuario_id");

                    b.Property<Guid>("SupervisorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("supervisor_usuario_id");

                    b.HasKey("SupervisorPersonalId")
                        .HasName("pk_supervisores_personal");

                    b.HasIndex("PersonalUsuarioId", "ClienteId");

                    b.HasIndex("SupervisorUsuarioId", "ClienteId");

                    b.HasIndex("ClienteId", "SupervisorUsuarioId", "PersonalUsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ux_supervisores_personal_activo")
                        .HasFilter("activo = TRUE");

                    b.ToTable("supervisores_personal", null, t =>
                        {
                            t.HasCheckConstraint("ck_supervisores_personal_distintos", "supervisor_usuario_id <> personal_usuario_id");

                            t.HasCheckConstraint("ck_supervisores_personal_fechas", "fecha_fin IS NULL OR fecha_fin >= fecha_inicio");
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.UsuarioCliente", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UsuarioId", "ClienteId")
                        .HasName("pk_usuarios_clientes");

                    b.HasIndex("ClienteId");

                    b.ToTable("usuarios_clientes", (string)null);
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.UsuarioClienteRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UsuarioId", "ClienteId", "RolId")
                        .HasName("pk_usuarios_clientes_roles");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios_clientes_roles", (string)null);
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.UsuarioFormulario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("FormularioId")
                        .HasColumnType("bigint")
                        .HasColumnName("formulario_id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UsuarioId", "FormularioId")
                        .HasName("pk_usuarios_formularios");

                    b.HasIndex("FormularioId");

                    b.ToTable("usuarios_formularios", (string)null);
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.UsuarioTienda", b =>
                {
                    b.Property<long>("UsuarioTiendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_tienda_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UsuarioTiendaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("TiendaCadenaKey")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("tienda_cadena_key");

                    b.Property<string>("TipoAsignacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_asignacion");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("UsuarioTiendaId")
                        .HasName("pk_usuarios_tiendas");

                    b.HasIndex("ClienteId", "TiendaCadenaKey");

                    b.HasIndex("UsuarioId", "ClienteId", "TiendaCadenaKey", "TipoAsignacion")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_tiendas_asignacion_activa")
                        .HasFilter("activo = TRUE");

                    b.ToTable("usuarios_tiendas", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_tiendas_fechas", "fecha_fin IS NULL OR fecha_fin >= fecha_inicio");
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("sello_concurrencia");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_normalizado");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_nombre_normalizado");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Activo = true,
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000001",
                            Descripcion = "Administra clientes, usuarios, formularios y reportes.",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Activo = true,
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000002",
                            Descripcion = "Supervisa personal y tiendas asignadas.",
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Activo = true,
                            ConcurrencyStamp = "10000000-0000-0000-0000-000000000003",
                            Descripcion = "Registra actividades y evidencias de campo.",
                            Name = "Impulsadora",
                            NormalizedName = "IMPULSADORA"
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("intentos_fallidos");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("sello_concurrencia");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correo");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("correo_confirmado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("bloqueo_habilitado");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueo_hasta");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correo_normalizado");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_usuario_normalizado");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("telefono_confirmado");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("sello_seguridad");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("doble_factor_habilitado");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_documento")
                        .HasFilter("documento IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_usuarios_correo_normalizado");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_nombre_normalizado");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.ArchivoFormulario", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.ClienteTienda", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sysbimbo.Api.Models.Entities.DimTiendaMaestraExport", null)
                        .WithMany()
                        .HasForeignKey("TiendaCadenaKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.Formulario", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.FormularioOpcion", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.Formulario", "Formulario")
                        .WithMany("Opciones")
                        .HasForeignKey("FormularioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formulario");
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.FormularioRegistro", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.JornadaUsuario", null)
                        .WithMany()
                        .HasForeignKey("JornadaUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SupervisorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sysbimbo.Api.Models.Entities.ClienteTienda", null)
                        .WithMany()
                        .HasForeignKey("ClienteId", "TiendaCadenaKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sysbimbo.Api.Models.Entities.Formulario", null)
                        .WithMany()
                        .HasForeignKey("FormularioId", "ClienteId")
                        .HasPrincipalKey("FormularioId", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.FormularioRegistroArchivo", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.ArchivoFormulario", null)
                        .WithMany()
                        .HasForeignKey("ArchivoFormularioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sysbimbo.Api.Models.Entities.FormularioRegistro", null)
                        .WithMany()
                        .HasForeignKey("FormularioRegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.FotoMaterialImpulso", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.MaterialImpulsoTienda", "MaterialImpulsoTienda")
                        .WithMany("Fotos")
                        .HasForeignKey("MaterialImpulsoTiendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fotos_material");

                    b.Navigation("MaterialImpulsoTienda");
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.JornadaUsuario", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.ArchivoFormulario", null)
                        .WithMany()
                        .HasForeignKey("FotoInicioArchivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SupervisorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sysbimbo.Api.Models.Entities.ClienteTienda", null)
                        .WithMany()
                        .HasForeignKey("ClienteId", "TiendaCadenaKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sysbimbo.Api.Models.Entities.Formulario", null)
                        .WithMany()
                        .HasForeignKey("FormularioId", "ClienteId")
                        .HasPrincipalKey("FormularioId", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.MaterialImpulsoTienda", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.DimTiendaMaestraExport", null)
                        .WithMany()
                        .HasForeignKey("TiendaCadenaKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_materiales_tienda");
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.SupervisorPersonal", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.UsuarioCliente", null)
                        .WithMany()
                        .HasForeignKey("PersonalUsuarioId", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sysbimbo.Api.Models.Entities.UsuarioCliente", null)
                        .WithMany()
                        .HasForeignKey("SupervisorUsuarioId", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.UsuarioCliente", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.UsuarioClienteRol", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sysbimbo.Api.Models.Entities.UsuarioCliente", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.UsuarioFormulario", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.Formulario", null)
                        .WithMany()
                        .HasForeignKey("FormularioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sysbimbo.Api.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.UsuarioTienda", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.ClienteTienda", null)
                        .WithMany()
                        .HasForeignKey("ClienteId", "TiendaCadenaKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sysbimbo.Api.Models.Entities.UsuarioCliente", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.Formulario", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.MaterialImpulsoTienda", b =>
                {
                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
