// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sysbimbo.Api.Data;

#nullable disable

namespace Sysbimbo.Api.Data.Migrations.FormularioPostgres
{
    [DbContext(typeof(FormularioDbContext))]
    partial class FormularioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.DimTiendaMaestraExport", b =>
                {
                    b.Property<string>("TiendaCadenaKey")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("tienda_cadena_key");

                    b.Property<string>("Cadena")
                        .HasColumnType("text")
                        .HasColumnName("cadena");

                    b.Property<string>("Canal")
                        .HasColumnType("text")
                        .HasColumnName("canal");

                    b.Property<long?>("CantidadRegistros")
                        .HasColumnType("bigint")
                        .HasColumnName("cantidad_registros");

                    b.Property<string>("CodigoTiendaB2B")
                        .HasColumnType("text")
                        .HasColumnName("codigo_tienda_b2b");

                    b.Property<string>("CodigoTiendaB2BPrefijo")
                        .HasColumnType("text")
                        .HasColumnName("codigo_tienda_b2b_prefijo");

                    b.Property<string>("Formato")
                        .HasColumnType("text")
                        .HasColumnName("formato");

                    b.Property<string>("FuenteTienda")
                        .HasColumnType("text")
                        .HasColumnName("fuente_tienda");

                    b.Property<string>("Gestor")
                        .HasColumnType("text")
                        .HasColumnName("gestor");

                    b.Property<string>("LimaProvincias")
                        .HasColumnType("text")
                        .HasColumnName("lima_provincias");

                    b.Property<string>("NombreTienda")
                        .HasColumnType("text")
                        .HasColumnName("nombre_tienda");

                    b.Property<string>("NombreTiendaBimbo")
                        .HasColumnType("text")
                        .HasColumnName("nombre_tienda_bimbo");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("provincia");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("Ruta")
                        .HasColumnType("text")
                        .HasColumnName("ruta");

                    b.Property<string>("Supervisor")
                        .HasColumnType("text")
                        .HasColumnName("supervisor");

                    b.Property<string>("TipoLocal")
                        .HasColumnType("text")
                        .HasColumnName("tipo_local");

                    b.Property<DateTime?>("UltimaFecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultima_fecha");

                    b.Property<string>("Vendedor")
                        .HasColumnType("text")
                        .HasColumnName("vendedor");

                    b.HasKey("TiendaCadenaKey")
                        .HasName("pk_tiendas");

                    b.HasIndex("Formato")
                        .HasDatabaseName("ix_tiendas_formato");

                    b.HasIndex("NombreTiendaBimbo")
                        .HasDatabaseName("ix_tiendas_nombre_bimbo");

                    b.ToTable("tiendas", (string)null);
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.FotoMaterialImpulso", b =>
                {
                    b.Property<long>("FotoMaterialImpulsoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("foto_material_impulso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FotoMaterialImpulsoId"));

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaCaptura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_captura")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("MaterialImpulsoTiendaId")
                        .HasColumnType("bigint")
                        .HasColumnName("material_impulso_tienda_id");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nombre_archivo");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TiendaCadenaKey")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("tienda_cadena_key");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_contenido");

                    b.HasKey("FotoMaterialImpulsoId")
                        .HasName("pk_fotos_material_impulso");

                    b.HasIndex("MaterialImpulsoTiendaId", "FechaCaptura")
                        .HasDatabaseName("ix_fotos_material_fecha");

                    b.ToTable("fotos_material_impulso", null, t =>
                        {
                            t.HasCheckConstraint("ck_fotos_material_impulso_tamano", "tamano_bytes > 0");
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.MaterialImpulsoTienda", b =>
                {
                    b.Property<long>("MaterialImpulsoTiendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("material_impulso_tienda_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MaterialImpulsoTiendaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CuotaDiaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cuota_diaria");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreMaterial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_material");

                    b.Property<string>("TiendaCadenaKey")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("tienda_cadena_key");

                    b.HasKey("MaterialImpulsoTiendaId")
                        .HasName("pk_materiales_impulso_tienda");

                    b.HasIndex("TiendaCadenaKey", "Activo")
                        .HasDatabaseName("ix_materiales_tienda_activo");

                    b.HasIndex("TiendaCadenaKey", "NombreMaterial")
                        .IsUnique()
                        .HasDatabaseName("ux_materiales_tienda_nombre_activo")
                        .HasFilter("activo = TRUE");

                    b.ToTable("materiales_impulso_tienda", null, t =>
                        {
                            t.HasCheckConstraint("ck_materiales_impulso_tienda_cuota_diaria", "cuota_diaria >= 0");
                        });
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.FotoMaterialImpulso", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.MaterialImpulsoTienda", "MaterialImpulsoTienda")
                        .WithMany("Fotos")
                        .HasForeignKey("MaterialImpulsoTiendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fotos_material");

                    b.Navigation("MaterialImpulsoTienda");
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.MaterialImpulsoTienda", b =>
                {
                    b.HasOne("Sysbimbo.Api.Models.Entities.DimTiendaMaestraExport", null)
                        .WithMany()
                        .HasForeignKey("TiendaCadenaKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_materiales_tienda");
                });

            modelBuilder.Entity("Sysbimbo.Api.Models.Entities.MaterialImpulsoTienda", b =>
                {
                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
