CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260811191733_InitialFormularioPostgres') THEN
    CREATE TABLE tiendas (
        tienda_cadena_key character varying(450) NOT NULL,
        codigo_tienda_b2b_prefijo text,
        codigo_tienda_b2b text,
        nombre_tienda text,
        nombre_tienda_bimbo text,
        canal text,
        cadena text,
        formato text,
        tipo_local text,
        lima_provincias text,
        region text,
        provincia text,
        ruta text,
        supervisor text,
        gestor text,
        vendedor text,
        ultima_fecha timestamp without time zone,
        cantidad_registros bigint,
        fuente_tienda text,
        CONSTRAINT pk_tiendas PRIMARY KEY (tienda_cadena_key)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260811191733_InitialFormularioPostgres') THEN
    CREATE TABLE materiales_impulso_tienda (
        material_impulso_tienda_id bigint GENERATED BY DEFAULT AS IDENTITY,
        tienda_cadena_key character varying(450) NOT NULL,
        nombre_material character varying(200) NOT NULL,
        descripcion character varying(500),
        cuota_diaria integer NOT NULL DEFAULT 0,
        activo boolean NOT NULL DEFAULT TRUE,
        fecha_creacion timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT pk_materiales_impulso_tienda PRIMARY KEY (material_impulso_tienda_id),
        CONSTRAINT ck_materiales_impulso_tienda_cuota_diaria CHECK (cuota_diaria >= 0),
        CONSTRAINT fk_materiales_tienda FOREIGN KEY (tienda_cadena_key) REFERENCES tiendas (tienda_cadena_key) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260811191733_InitialFormularioPostgres') THEN
    CREATE TABLE fotos_material_impulso (
        foto_material_impulso_id bigint GENERATED BY DEFAULT AS IDENTITY,
        material_impulso_tienda_id bigint NOT NULL,
        tienda_cadena_key character varying(450) NOT NULL,
        nombre_archivo character varying(260) NOT NULL,
        tipo_contenido character varying(100) NOT NULL,
        tamano_bytes bigint NOT NULL,
        contenido bytea NOT NULL,
        fecha_captura timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT pk_fotos_material_impulso PRIMARY KEY (foto_material_impulso_id),
        CONSTRAINT ck_fotos_material_impulso_tamano CHECK (tamano_bytes > 0),
        CONSTRAINT fk_fotos_material FOREIGN KEY (material_impulso_tienda_id) REFERENCES materiales_impulso_tienda (material_impulso_tienda_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260811191733_InitialFormularioPostgres') THEN
    CREATE INDEX ix_fotos_material_fecha ON fotos_material_impulso (material_impulso_tienda_id, fecha_captura);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260811191733_InitialFormularioPostgres') THEN
    CREATE INDEX ix_materiales_tienda_activo ON materiales_impulso_tienda (tienda_cadena_key, activo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260811191733_InitialFormularioPostgres') THEN
    CREATE UNIQUE INDEX ux_materiales_tienda_nombre_activo ON materiales_impulso_tienda (tienda_cadena_key, nombre_material) WHERE activo = TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260811191733_InitialFormularioPostgres') THEN
    CREATE INDEX ix_tiendas_formato ON tiendas (formato);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260811191733_InitialFormularioPostgres') THEN
    CREATE INDEX ix_tiendas_nombre_bimbo ON tiendas (nombre_tienda_bimbo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260811191733_InitialFormularioPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260811191733_InitialFormularioPostgres', '8.0.8');
    END IF;
END $EF$;
COMMIT;
